language: ruby
branches:
  only:
    - master
before_script:
  - mysql -e 'create database delayed_job_test;'
  - mysql --version
  - psql -c 'create database delayed_job_test;' -U postgres
script: bundle exec $COMMAND
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS -Xcli.debug=true --debug"
    - COMMAND=rspec
gemfile: # Supported
  - gemfiles/mysql2/4-2.gemfile
  - gemfiles/mysql2/5-0.gemfile
  - gemfiles/mysql2/5-1.gemfile
  - gemfiles/postgresql/4-2.gemfile
  - gemfiles/postgresql/5-0.gemfile
  - gemfiles/postgresql/5-1.gemfile
  - gemfiles/sqlite3/4-2.gemfile
  - gemfiles/sqlite3/5-0.gemfile
  - gemfiles/sqlite3/5-1.gemfile
rvm: # Supported
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - jruby-9.1.8.0

jdk: oraclejdk8

matrix:
  allow_failures:
    - rvm: jruby-head # Future
    - rvm: rbx-2 # Parallel dimension
    - rvm: ruby-head # Future
    - gemfile: gemfiles/mysql2/master.gemfile # Future
    - gemfile: gemfiles/postgresql/master.gemfile # Future
    - gemfile: gemfiles/sqlite3/master.gemfile # Future
    # The two combinations below are currently broken. We should stop allowing
    # failure as the issue is resolved. See:
    # https://github.com/jruby/activerecord-jdbc-adapter/issues/700
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/mysql2/5-1.gemfile
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/postgresql/5-1.gemfile

  include:
    #
    # Rubocop
    #
    - rvm: 2.5.0
      gemfile: Gemfile
      env:
        - COMMAND=rubocop
    #
    # The future
    #
    # MRI 2.5.0
    - rvm: 2.5.0
      gemfile: gemfiles/mysql2/5-1.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/postgresql/5-1.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/sqlite3/5-1.gemfile
    # Active Record head
    - gemfile: gemfiles/mysql2/master.gemfile
      rvm: 2.4.3
    - gemfile: gemfiles/postgresql/master.gemfile
      rvm: 2.4.3
    - gemfile: gemfiles/sqlite3/master.gemfile
      rvm: 2.4.3
    # MRI Ruby head
    - rvm: ruby-head
      gemfile: gemfiles/mysql2/5-1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/postgresql/5-1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/sqlite3/5-1.gemfile
    # JRuby head
    - rvm: jruby-head
      gemfile: gemfiles/mysql2/5-1.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/postgresql/5-1.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/sqlite3/5-1.gemfile
    #
    # The past
    #
    # EOL Active Record
    - gemfile: gemfiles/mysql2/3-0.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/mysql2/3-1.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/mysql2/3-2.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/mysql2/4-0.gemfile
      rvm: 2.3.6
    - gemfile: gemfiles/mysql2/4-1.gemfile
      rvm: 2.3.6
    - gemfile: gemfiles/postgresql/3-0.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/postgresql/3-1.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/postgresql/3-2.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/postgresql/4-0.gemfile
      rvm: 2.3.6
    - gemfile: gemfiles/postgresql/4-1.gemfile
      rvm: 2.3.6
    - gemfile: gemfiles/sqlite3/3-0.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/sqlite3/3-1.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/sqlite3/3-2.gemfile
      rvm: 2.2.9
    - gemfile: gemfiles/sqlite3/4-0.gemfile
      rvm: 2.3.6
    - gemfile: gemfiles/sqlite3/4-1.gemfile
      rvm: 2.3.6
    #
    # The parallel dimension
    #
    # Rubinius
    - gemfile: gemfiles/mysql2/5-1.gemfile
      rvm: rbx-2
    - gemfile: gemfiles/postgresql/5-1.gemfile
      rvm: rbx-2
    - gemfile: gemfiles/sqlite3/5-1.gemfile
      rvm: rbx-2

sudo: false
